In [66]:
import pandas as pd 
import math
from itertools import combinations
from scipy import stats

In [67]:
#data_grch38
t2t

          LD1       LD2       LD3       LD4
AFR  9.318272 -3.750575  0.422802  0.141920
AMR  0.942198  4.615892 -2.347095 -1.369690
EAS -9.449936 -5.540961 -0.951264  0.058969
EUR -0.672804  6.249904 -1.583502  1.910297
SAS -3.746798  3.537606  4.704357 -0.286158

In [68]:
grch38 = pd.read_csv('../data/centroids_grch38.csv', index_col=0)
grch38

          LD1       LD2       LD3       LD4
AFR  8.380793 -1.130336 -0.034707  0.000830
AMR -3.436474 -1.575974  0.750231  0.056807
EAS -1.634522  6.231146 -0.180648  0.024953
EUR -5.298673 -4.712199 -0.749231  0.061987
SAS -3.544717 -0.874152  0.037872 -0.151391

In [69]:
combination_names = []
for i in list(combinations(grch38.index,2)):
    combination_names.append(i[0]+str('-')+i[1])

In [70]:
distance_dt_grch38 = []
combination_regions = list(combinations([0,1,2,3,4],2))
for region in combination_regions:
        distance = (math.dist([grch38['LD1'][region[0]], grch38['LD2'][region[0]]],[grch38['LD1'][region[1]], grch38['LD2'][region[1]]]))  
    #math.dist((dt_groupped[region[0]]), (dt_groupped[region[1]]))
        distance_dt_grch38.append(distance)

/var/folders/05/4pfxtbrs5459ytz3j1jhcgt00000gn/T/ipykernel_27964/1067319861.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  distance = (math.dist([grch38['LD1'][region[0]], grch38['LD2'][region[0]]],[grch38['LD1'][region[1]], grch38['LD2'][region[1]]]))

In [71]:
distance_dt_grch38 = pd.DataFrame(distance_dt).set_axis(combination_names)
distance_dt_grch38

ValueError: Length mismatch: Expected axis has 20 elements, new values have 10 elements

In [72]:
## T2t 
t2t = pd.read_csv('../data/centroids_t2t.csv', index_col=0)

combination_names = []
for i in list(combinations(t2t.index,2)):
    combination_names.append(i[0]+str('-')+i[1])

distance_dt_t2t = []
combination_regions = list(combinations([0,1,2,3,4],2))
for region in combination_regions:
        distance = (math.dist([t2t['LD1'][region[0]], t2t['LD2'][region[0]]],[t2t['LD1'][region[1]], t2t['LD2'][region[1]]]))  
    #math.dist((dt_groupped[region[0]]), (dt_groupped[region[1]]))
        distance_dt_t2t.append(distance)

#distance_dt_t2t = pd.DataFrame(distance_dt).set_axis(combination_names)
distance_dt_t2t

/var/folders/05/4pfxtbrs5459ytz3j1jhcgt00000gn/T/ipykernel_27964/2878501119.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  distance = (math.dist([t2t['LD1'][region[0]], t2t['LD2'][region[0]]],[t2t['LD1'][region[1]], t2t['LD2'][region[1]]]))

[11.838766537949079,
 18.853411551969632,
 14.136165433419928,
 14.960401881204781,
 14.53128125493123,
 2.297438602541749,
 4.811380876454071,
 14.699066371402601,
 10.721294711281688,
 4.099512374286797]

In [73]:
t2t

          LD1       LD2       LD3       LD4
AFR  9.318272 -3.750575  0.422802  0.141920
AMR  0.942198  4.615892 -2.347095 -1.369690
EAS -9.449936 -5.540961 -0.951264  0.058969
EUR -0.672804  6.249904 -1.583502  1.910297
SAS -3.746798  3.537606  4.704357 -0.286158

In [53]:
# Wilcoxon to test differences

In [86]:
statistic, p_value = stats.wilcoxon(distance_dt_t2t,distance_dt_grch38, alternative='greater')

# Print the results
print(f"Wilcoxon statistic: {statistic}")
print(f"P-value: {p_value}")

Wilcoxon statistic: 47.0
P-value: 0.0244140625

In [87]:
statistic, p_value = stats.ttest_rel(distance_dt_grch38, distance_dt_t2t)

# Print the results
print(f"T-test statistic: {statistic}")
print(f"P-value: {p_value}")

T-test statistic: -2.855992834338927
P-value: 0.01890351459357883